### ISSUE TITLE
[retro-contest] error at bridge.py on Windows

### ISSUE THREAD

**Issue by decoderkurt** [openai/retro-contest#19]
I am using windows 10.  tried to retro-contest-run rainbow agent.
while running, I got error like this

D:\project>retro-contest run --agent  $DOCKER_REGISTRY/rainbow_agent:v1 --results-dir results --no-nv --use-host-data SonicTheHedgehog-Genesis GreenHillZone.Act1

Traceback (most recent call last):
  File "/root/compo/agent.py", line 46, in <module>
    main()
  File "/root/compo/agent.py", line 22, in main
    env = AllowBacktracking(make_env(stack=False, scale_rew=False))
  File "/root/compo/sonic_util.py", line 15, in make_env
    env = grc.RemoteEnv('tmp/sock')
  File "/root/venv/lib/python3.5/site-packages/gym_remote/client.py", line 15, in __init__
    self.bridge.connect()
  File "/root/venv/lib/python3.5/site-packages/gym_remote/bridge.py", line 251, in connect
    self.sock.connect(sock_path)
FileNotFoundError: [Errno 2] No such file or directory
Remote exited uncleanly: 1
Agent exited uncleanly 1

**Comment by endrift** [comment]
What are the contents of `results/remote-stderr.txt`?

**Comment by decoderkurt** [comment]
This is my results/remote-stderr.txt

Traceback (most recent call last):
  File "/root/venv/lib/python3.5/site-packages/retro_contest/local.py", line 11, in make
    env = retro.make(game, state, scenario='contest', use_restricted_actions=use_restricted_actions)
  File "/root/venv/lib/python3.5/site-packages/retro/__init__.py", line 120, in make
    return RetroEnv(game, state, **kwargs)
  File "/root/venv/lib/python3.5/site-packages/retro/retro_env.py", line 70, in __init__
    with gzip.open(os.path.join(game_path, state), 'rb') as fh:
  File "/usr/lib/python3.5/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/data/SonicTheHedgehog-Genesis/MarbleGardenZone.Act2.state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/bin/retro-contest-remote", line 9, in <module>
    load_entry_point('retro-contest-support==0.1.0', 'console_scripts', 'retro-contest-remote')()
  File "/root/venv/lib/python3.5/site-packages/retro_contest/remote.py", line 98, in main
    args.func(args)
  File "/root/venv/lib/python3.5/site-packages/retro_contest/remote.py", line 41, in run_args
    daemonize=args.daemonize)
  File "/root/venv/lib/python3.5/site-packages/retro_contest/remote.py", line 30, in run
    env = make(game, state, bk2dir, monitordir, discrete_actions, socketdir)
  File "/root/venv/lib/python3.5/site-packages/retro_contest/remote.py", line 14, in make
    env = retro_contest.local.make(game, state, discrete_actions=discrete_actions, bk2dir=bk2dir)
  File "/root/venv/lib/python3.5/site-packages/retro_contest/local.py", line 13, in make
    env = retro.make(game, state, use_restricted_actions=use_restricted_actions)
  File "/root/venv/lib/python3.5/site-packages/retro/__init__.py", line 120, in make
    return RetroEnv(game, state, **kwargs)
  File "/root/venv/lib/python3.5/site-packages/retro/retro_env.py", line 70, in __init__
    with gzip.open(os.path.join(game_path, state), 'rb') as fh:
  File "/usr/lib/python3.5/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/data/SonicTheHedgehog-Genesis/MarbleGardenZone.Act2.state'

-------------------
this is agent-stderr,txt 

Traceback (most recent call last):
  File "/root/compo/agent.py", line 102, in <module>
    main()
  File "/root/compo/agent.py", line 78, in main
    env = AllowBacktracking(make_env(stack=False, scale_rew=False))
  File "/root/compo/custom_sonic_util.py", line 15, in make_env
    env = grc.RemoteEnv('tmp/sock')
  File "/root/venv/lib/python3.5/site-packages/gym_remote/client.py", line 15, in __init__
    self.bridge.connect()
  File "/root/venv/lib/python3.5/site-packages/gym_remote/bridge.py", line 251, in connect
    self.sock.connect(sock_path)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by endrift** [comment]
Did you install gym-retro and the ROMs on the host?

**Comment by decoderkurt** [comment]
simple agent works with bk2 and monitor.cvs files in result directory. 
I think gym-retro and ROM is installed without problems. 
------
D:\project\simple-agent>retro-contest run --agent  $DOCKER_REGISTRY/simple-agent:v1 --results-dir results --no-nv --use-host-data SonicTheHedgehog-Genesis GreenHillZone.Act1
connecting to remote environment
starting episode
episode complete
episode complete
episode complete
episode complete

**Comment by decoderkurt** [comment]
I found the reason. there were some errors in the .state name. I modified state name and it worked! 
thanks
