### ISSUE TITLE
Error occur in image openai/retro-agent:pytorch-0.3

### ISSUE THREAD

**Issue by Officium** [openai/retro-contest#25]
Code
```python
import gym_remote.client as grc


if __name__ == '__main__':
    for i in range(10):
        env = grc.RemoteEnv('tmp/sock')
        env.reset()
        while True:
            env.step(env.action_space.sample())
```

Error
```
Traceback (most recent call last):
  File "/root/compo/main.py", line 15, in <module>
    env.step(env.action_space.sample())
  File "/root/venv/lib/python3.5/site-packages/gym_remote/client.py", line 35, in step
    self.bridge.recv()
  File "/root/venv/lib/python3.5/site-packages/gym_remote/bridge.py", line 323, in recv
    self._message_handlers[message['type']](message['content'])
  File "/root/venv/lib/python3.5/site-packages/gym_remote/bridge.py", line 165, in exception
    raise gre.make(message['exception'], message['reason'])
gym_remote.exceptions.ResetError: None
Agent exited uncleanly 1
```

DockerFile
```
FROM openai/retro-agent:pytorch-0.3

RUN apt-get update --fix-missing

# Requirements
RUN . ~/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install Pillow

# File copy
COPY src/*.py ./

# RUN
CMD ["python", "-u", "/root/compo/main.py"]
```

**Comment by endrift** [comment]
You need to call reset before the first step.
